### ISSUE TITLE
Clarify ACL

### ISSUE THREAD

**Issue by elf-pavlik** [w3c-social/activitypub#28]
Based on https://github.com/w3c-social/activitypump/blob/master/userstories/user-posts-a-note.md

If server doesn't create an artifact of who it send note to. When followers collection changes people added afterwards will gain access to note.

**Comment by cwebber** [comment]
The section is incomplete (see #27) but I believe this is specified as being the "followers" list (all people who have subscribed to this user):

> Every actor MUST have a followers collection. This is the default recipient list for otherwise unaddressed activities [...]

Does that answer your first question?  It looks like you're also asking about making it clear what happens when people are added to a group later.  My understanding is, it won't show up in their inbox, but they can access the object now if they know the URL.

**Comment by elf-pavlik** [comment]
> I think what is most likely is that the server would assume the user does not have access, this is because I think the server would build an access list at the time of sending.

Personally I don't support particular choice here but see need for explaining this aspect of ACL

**Comment by cwebber** [comment]
I added a whole section clarifying the state of access control.
