### ISSUE TITLE
"to": "http://as.schema/public" vs. "target": "MY OUTBOX URI"

### ISSUE THREAD

**Issue by elf-pavlik** [w3c-social/activitypub#29]
based on: https://github.com/w3c-social/activitypump/blob/master/userstories/following-a-person.md

it introduces a special ~"well known" URI while same functionality might work by instead using "to" use "target": "MY OUTBOX URI"

**Comment by xray7224** [comment]
Just for clarity you mean to do something like this:

```
{
    "@context": "http://www.w3.org/ns/activitystreams",
    "@type": "Add",
    "object": {
        "@type": "Note",
        "content": "Hello world",
    },
    "target": {
        "@id": "https://example.com/user/tsyesika/feed",

**Comment by rhiaro** [comment]
If outboxes are discoverable by dereferencing an actor URI (which is what it looks like to me in the spec currently), the outbox is not at a fixed 'well known' URL but can be found by dereferencing the value of `to`, right? So using `target` wouldn't be necessary.

**Comment by elf-pavlik** [comment]
https://github.com/w3c-social/activitypump/blob/master/userstories/following-a-person.md#3-4-seeing-that-new-persons-content

uses: `"to": "http://activityschema.org/collection/public"` which has nothing to do with a particular list of someone's followers, if one prefers to use 'audience targeting' instead of explicit feed(s), maybe simply using URI of one's own followers collection makes more sense here?

**Comment by tsyesika** [comment]
Okay so I agree it's not ideal to have a well known URL to specify something is public. I however think this proposed solution doesn't make much sense and doesn't really fit with the target definition specified in AS 2.0 https://www.w3.org/TR/activitystreams-vocabulary/#dfn-target

I think this really confuses the specification as `target` is never used for audience targetting or ACL anywhere else so it doesn't really make much sense to start using it now. The "outbox" isn't just for "public" activities either, all audience targeting gets added to the outbox, the outbox is just a list of sent activities from this user. Finally it really complicates things for activities where targetting is used in the current sense being the destination of the verb for example in the case where a user is adding a photo to a collection and wants to specify that it is also a "public" activity, how does one do that as `target` is used to specify which collection the photo is being added to.

I'm closing this for now, not because I don't think there is an issue using the well known public id but this solution doesn't make much sense and I can't think of a good way to solve this problem. Please re-open if you think I'm wrong or have an alternative proposition.
