### ISSUE TITLE
'Silent' posting

### ISSUE THREAD

**Issue by rhiaro** [w3c-social/activitypub#38]
Would it be useful for a user to be able to post an object (so it appears publicly on their feed, or is visible to their followers when a follower visits their feed directly, or whatever their preferred ACL settings are), but the activity does *not* get explicitly delivered to an audience?

**Comment by xray7224** [comment]
I agree this would be hugely useful. I propose removing the section that if a "public" also means federating to Followers, if it's just "Public" it shouldn't be federated to anyone.

**Comment by cwebber** [comment]
I'm not sure what the use case is... could you clarify?

**Comment by tsyesika** [comment]
One might post a their holiday photos or something, happy for them to public for them to link to others but not really want to send them to anyone in particular. This also could be used for other activities such as "check-in" type activities where people say they're at a location, they're happy for people to look but they don't really care to push it out to any particular audience.

Any activity which you want to be viable by anyone, linkable but you it doesn't have an explicit audience you want it to be federated to.

**Comment by cwebber** [comment]
Ok, there's some argument for that; I guess there's some risk of bloat but maybe it's useful enough.  It would be nice if there's some suggested mockups of what this would look like in terms of the AS document structure.

**Comment by dmitrizagidulin** [comment]
+1 to this, it seems like a really useful er, use case.

**Comment by tsyesika** [comment]
I think this actually makes the document simpler. The spec can just say you federate to whatever audience is specified and, if no audience is specified then don't federate to anyone. I'd argue the current system where it federated by default to "followers" if no audience is specified seems complicate things (not by a lot, but somewhat).

If an implementation wants a default they can list a default when asking the user to make an activity and the user can decide if that default suits them, the specification shouldn't mandate everything has to have an audience, it doesn't make much sense to me to require that.

**Comment by cwebber** [comment]
But you'd still need to flag somehow that you _did_ expect that it's public.  Currently "Followers" collection says "this should be public".  I think _reducing_ recipients resulting in something being public would be surprising.

Then again it might match what I expect from the MediaGoblin federation-compatible submit page you've written...

**Comment by cwebber** [comment]
Sorry I'm being confused.  I should have said "Public" when I said "Followers".

**Comment by tsyesika** [comment]
So. Currently the specifications says:

> If no recipients are specified, the user's preferred default audience should be applied. The default value for the default audience is implementation specific but MAY be the user's followers collection

This leaves it pretty vague, can the users default values be just "public" and if so that might mean this is achievable. I however think i might have intentionally left the audience blank or just as "public" and that isn't me inviting the application to choose to audience for me, this could be because I don't want them federated to everyone.

A use-case to this is I have 200 or so pictures from a trip up to Kiruna, I want to upload at some point and I'd like them to be public so people can, if they so choose go and look at them but I don't want to spam all my followers with my 200 holiday photos. I could even see this extending to not wanting an audience at all including "public", I could imagine having private images I upload who I don't want to show anyone, maybe as a phone instant upload type situation. In this situation maybe at a later date I'd like to update the audience with an "update" activity which would trigger a federation. This would be really useful for Mediagoblin, in my opinion.

**Comment by cwebber** [comment]
That's true about the private for-the-users-eye-only mediagoblin view.  Someone who wants to keep MediaGoblin as a photo archiving system but wants to keep a private set of photos about a personal moment may want to use such a feature.

Maybe we can say that this is "implementation defined", and suggest either posting it as "Public only" or allow an implementation to do this kind of private posting.

This is client to server, and probably it's safe enough to let this be implementation independent and provide wiggle room.  It might not even be a good idea to try to decide for implementers here.
