### ISSUE TITLE
Expected response for POST {Update,Delete} activity with object: 'http://facebook.com'

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypub#48]
originally: https://hypothes.is/a/Wu9YqHthSSWSosMHZztI5A

> The Update activity is used when updating an already existing object. The object should be modified to reflect the new structure in defined in the update activity.

What if the object's @id is 'http://facebook.com' (or another thing that the outbox server can't know how to update?). 400 Response? and it doesn't get in outbox?

But what if I, say, did update some resource through another program, and want that update to appear in my outbox?

In general, submitting an activity to trigger a side effects in a federated model seems like a diffcult thing to get right... It seems more tractable to lay out a way for other servers on which you update things to deliver a receipt for that activity to your outbox.

**Comment by cwebber** [comment]
This is a serious issue that's much easier if we permit same-origin only for inbox/outbox streams.  If we permit same-origin only, we can trust that if we can verify that the update activity came from the same source as the object being updated, and we verify that those objects really did come from there (mandated in the spec anyway), we can trust updating our local definition.  However that prevents follow-your-nose off-server hosting of activitypump type endpoints, a-la a "disqus-style" deferring of federation work elsewhere.  I know @tantek and others really are super pro-static-site support, so that gives me pause in taking that approach.

One other way to do it is to re-fetch the object that's being updated once we have been told that it has been, and verify that it has really been updated to the thing we've been told it is.  In a sense, this makes the payload of what it's been updated to mostly meaningless; we just as well could have backtracked to the original source.  But there are some arguments that this is commonly the case and we should encourage more FYN and not do inline embedding so much in activitypump, where possible.  (In this case, if the source of the update came from the same origin, then we could consider not fetching the object as an optimization of sorts.  I'm not sure if that's worth it.)

A decision should be made and we should update the document for certain.

**Comment by cwebber** [comment]
By the way, I think the "same origin only" restriction is the current state of affairs in pump.io, but @evanp can clarify.

**Comment by cwebber** [comment]
F2F discussion: Assuming the profile is hosted on same origin, we can trust its judgements of what endpoints it thinks are safe.

CSP might be useful for scripted display of comments on a static site.

**Comment by tsyesika** [comment]
Based on this analysis and that we will clarify things with an new verification of content section in issue #81 we can close this issue.
